application: mayday-pac-teams
version: 1
runtime: python27
api_version: 1
threadsafe: yes

builtins:
- remote_api: on

handlers:
- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/*

- url: /static/
  static_dir: static/

- url: /site-admin(|/.*)
  script: main.app
  login: admin

- url: .*
  script: main.app
  secure: always

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
