application: teams-dev
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/*

- url: /static/
  static_dir: static/

- url: .*
  script: main.app
  secure: always

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
